### PR TITLE
Add Lera Pakhneva to the student list

### PR DESCRIPTION
**Pull request by valeriya-p**
Please update me with the latest list

### CODE REVIEW

**Comment by ava8katushka** [comment]
Please rename your pull request to Add Your Name to the student list.

**Comment by valeriya-p** [comment]
> Please rename your pull request to Add Your Name to the student list.

@ava8katushka could you please check :)

**Comment by ava8katushka** [comment]
All looks good, but another student was merged faster than you. Could you please resolve conflicts again?

**Comment by valeriya-p** [comment]
@ava8katushka done ;)

**Comment by ava8katushka** [comment]
Almost... a lot of people submit now. 
Please do again.

**Comment by valeriya-p** [comment]
more practice for me then ) please check

**Comment by ava8katushka** [comment]
Perfect!

**Pull request merged**
